### ISSUE TITLE
Switch to a membership model for services

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#120]
## The state of play

Right now we have a couple features where you have to be a donor to use them:

 - Real time search alerts are only provided if you donate at least $10/year.

 - You get 5 docket alerts for free (or 15 if you install RECAP). If you donate $5/month you get unlimited alerts.

Other than that, I think everything is free (though we try to get API users to license things). 

## How it'd feel as a user

In general, I think this should be a good change to make and a good re-framing for our users:

 - If you're a member you get some benefits.
 - If you're not a member you can still use practically everything.
 - If you don't want the benefits, you can still be a member.
 - If an organization wants to do corporate sponsorships, we can give their employees membership benefits.

## Tiers?

We can make this change without clawing back anything above by having tiers and making the lowest tier $5/month.

Non-members get:
 - 5 docket alerts  (or 15 if install RECAP).
 - Unlimited daily search alerts
 - No real time search alerts

$5/month tier 1 members get:
 - Unlimited docket alerts (currently costs $5/month, so this works well)
 - Unlimited real time search alerts (currently costs $10/year)
 - Stickers and a thank you note?

$10/month tier 2 members get the above, plus:
 - T-Shirt

$25/month tier 3 members get the above, plus:
 - Hoodie

Tiers 4, 5, and 6 don't include any more schwag, but they could be $50/month, $100/month, and $500/month.

## Other benefits?

I'm not sure how this will fit together with our bots.law or planned x-ray/clio integrations. Do members get discounts? Do users of Slack integration become defacto members? This will need to be sorted out.

## Taxes?

I'm checking with our tax preparer if doing memberships come with any tricky tax things we should know. 

## Looking at other orgs

Looking around:
 
 - EFF's [membership page](https://supporters.eff.org/donate/summer--SBD) has the tiers above and similar schwag. 

 - ACLU also lets you be a member, has no tiers (you can pay various amounts though), and gives no schwag or benefits.

 - AALL has a [bunch of membership things](https://www.aallnet.org/community/membership/benefits/), some of which they imply are part of the membership, but aren't, like the conference, I think. They have three tiers (four if you include their reduced rate for recently unemployed):

    ![image](https://github.com/freelawproject/free.law/assets/236970/7424fb54-9804-4dce-8749-1af5f230620a)

 - Investigative Reporters and Editors (IRE) provides five tiers at 1-4 years and roughly $60-70/year:

    ![image](https://github.com/freelawproject/free.law/assets/236970/84d6ab1f-f112-4f14-bb35-98437f3d4b88)

## Implementation

If we like the plan above, a few things to think about:

1. We'll want to move all of this over to free.law, not CourtListener or bots.law.

1. When somebody is a member, CourtListener shouldn't nag them to donate, right? It should know they're a member and say thank you. (Technically, this seems tricky, since it means having the membership info in CL and payments in free.law.)
   - This also applies to emails that we send.

1. The [donation page](https://www.courtlistener.com/profile/donations/) in our profile will probably need some tweaks.

1. Justia might still have a thing where people can be sponsors of FLP via their website. We should sort that out.

**Comment by mlissner** [comment]
Looks like we'll need some bylaw updates or at least research:

![image](https://github.com/freelawproject/free.law/assets/236970/5d64db0b-b2f3-46da-b9ed-0fd82ec7a154)

(Bylaws are here: https://free.law/pdf/policies/bylaws-amended-2017-11-05.pdf)

Note that the bylaw metadata in the PDF seems a bit sloppy too. Might want to clean that up while we're in them.

**Comment by jeniferw** [comment]
Freedom of the Press Foundation memberships - https://freedom.press/donate/membership-program/

**Comment by jeniferw** [comment]
For actual swag - we want to collect enough $ to cover cost before shipping out.
So I think if the gifts get mailed out after 3 months of membership, that would make sense.

Would like to figure out how to get law firms on this - without having to mail out a bunch of swag. 
Trying to decide between an ask of per US based attorney ($10/$25/$50/$100 annually per atty) or actual gift to determine level. ($10,000/$25,000/$50,0000/$100K annually)
For the firms on the [list](https://docs.google.com/spreadsheets/d/1O06jbDNJtAykWLITOARxZ1I_dA6D7ukBBH9XNGFiKbo/edit?usp=sharing) where I've found # of attys on their website, avg is 904 so total giving should be about the same either way - but per atty ask allows smaller firms to participate at larger levels - and the ask seems smaller when in initial conversations).

Thoughts might be:
Supporter = tier one benefits for all employees with your company email
Silver = tier 2 benefits
Gold = tier 2 benefits + recognition on website & in social media
Platinum = Tier 2 benefits + recognition + individualized benefits. (Unlikely we would get $100K level support from a firm or corporate donor without prior conversation & ask)
