### ISSUE TITLE
Establish membership levels

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#130]
Over in https://github.com/freelawproject/free.law/issues/120, I put a bunch of notes comparing some membership levels on orgs that came to mind. Let's use this issue to synthesize that and do an even better job. 

V1: Simple membership levels.
V2: Schwag (sweatshirts/hats/stickers/etc).

We just need to figure out what these levels are, and then we can make forms for it over in: https://github.com/freelawproject/free.law/issues/131

**Comment by jeniferw** [comment]
### Individual Membership Levels:

**Non-members get:**
- 5 docket alerts (or 15 if install RECAP)
- Unlimited daily search alerts
- No real-time search alerts

**Tier 1 - $10/monthly or $120/annual**
- Unlimited docket alerts (currently costs $5/month - will need to deal with increase or grandfather in or lower to $5/month)
- Unlimited real-time search alerts (currently costs $10/year - will also need to deal with increase)
- Stickers (Welcome packet??)

**Tier 2 - $25/monthly or $250/annual**
- Tier 1 benefits
- What else can we give???

**Tier 3 - $50/monthly or $500 annual**

**Tier 4 - $100/monthly or $1000/annual**

**Tier 5 - $500/monthly or $5000/annual**

**Platinum - $10,000+ annual** 

Eventually add schwag - t-shirts, totebags, hoodie, what else? and need to find source for reasonably priced drop ship on demand

**_Brainstorm ideas:_** 
- Recognition on website??
- Inclusion in a membership directory?

**Comment by mlissner** [comment]
We'll grandfather the $5/month folks, but maybe we can urge them to upgrade by asking nicely. Why not? We're a non-profit! 

One more thing to think about is that we're about to add RECAP Search Alerts, which are a BIG deal. I think they're enough to say that $10/month is the new price for real time search alerts (except for those grandfathered in), and it includes RECAP Alerts. 

So that'd be:

 - Non-members: Only Weekly RECAP Search Alerts
 - All other tiers: Count of real time RECAP search alerts allowed is 2× their monthly price. So, if you pay $10/month, you get 20 alerts.

**Comment by mlissner** [comment]
As for extra bonuses...I don't know. More schwag is the usual thing. I'm not sure if orgs/people want public recognition, but sure, if you contribute upwards of $5k, we can offer that, why not. 

Probably worth some creativity here, and I'm bad at that and out of juices for the day. We could look around a bit though and see what else comes up.

**Comment by jeniferw** [comment]
Print on Demand Swag options to research:
- https://www.swagmagic.com/
- https://www.swagup.com
- https://www.snappy.com - has API access via Zapier

**Comment by mlissner** [comment]
I mean, being able to automatically send people things via API would be pretty darned cool. I love that you're looking to API all the things.

![image](https://github.com/freelawproject/free.law/assets/236970/fbd6fc8c-03f4-497c-9722-23d14802546d)

I'd love to finally get schwag figured out generally, but I hesitate because our branding still needs work. So, like, do we really want to figure out hats and stuff when our design foundation isn't good yet? Maybe it's fine and we'll make some janky stuff at first that we can laugh about later. Our true supporters will wear anything, right???

**Comment by jeniferw** [comment]
Meetings with swag companies 10/19 - notes at

**Comment by jeniferw** [comment]
Need to figure out tax deduction implications for memberships
And look at all options for ensuring everyone who is entitled gets membership benefits
- current monthly $5 donors (grandfathered in)
- annual donors
- monthly donors
- annual memberships
- monthly memberships

**Comment by mlissner** [comment]
Something to think about here: I can 3D print things these days, so we could make somebody a 3D thank you note, with, say, their name in it or something at higher tiers. I feel like there's an opportunity here, but it's a bit of work...then again, Kelvin might do it for us.

**Comment by mlissner** [comment]
I'm closing this one. We can/should discuss swag and other benefits elsewhere. This is launched though, so I think it's fair to say it's done — for now!
