### ISSUE TITLE
Create a form infrastructure in Neon for membership sign up

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#131]
Once we've established membership levels in https://github.com/freelawproject/free.law/issues/130, we'll need to actually set them up in Neon. This includes a bunch of steps both user-facing and internal.

**Comment by jeniferw** [comment]
Questions to consider from #164:
- Membership Grace Period - do we want to provide a grace period for members to continue to access membership benefits for a short time after their payment ends? (I'm thinking maybe a week??)
- Sub-members (families, orgs, law firms) - 
          - do we want to set up firm donations as memberships? (Might make sense if we are including access to alerts as part of their annual donation)
          - do we want to let people others to their memberships??
- need to consider amount of annual donation that would give them membership benefits? ($10 a month or $100 per year? $120 per year? $150 per year?)
- if a membership has lapsed - do we want to have people renew based on the date of their previous renewal or based on the date of transaction (or renewal) whichever is later?

**Comment by mlissner** [comment]
> Grace period

Sure, why not.

> sub-members

I'm not sure I understand the sub-members thing, but in theory it'd be nice if we had a way for a firm to sign itself up and then we could provide bonuses to anybody with the firm email address, but that's hard for a number of reasons. 

We could do it in Neon though, and just not automate it. We currently have one firm that we give bonuses to by email address. We could continue doing CL by hand and Neon by hand if we wanted.

> Annual members

Sure, I guess doing ×10 instead of ×12 for annual memberships is fine.

> if membership has lapsed...

This is going to be a matter of days, right? I'm not sure it matters?

**Comment by jeniferw** [comment]
Membership form - https://donate.free.law/forms/membership

**Comment by mlissner** [comment]
I think we can call this done. Yay!
