### ISSUE TITLE
Add Oral Arguments to drop down

### ISSUE THREAD

**Issue by jeniferw** [freelawproject/free.law#141]
Add a link & sentence under the "Data" drop down at free.law
Link to https://free.law/projects/oral-arguments

**Comment by mlissner** [comment]
I've identified the problem: We lack a logo for oral arguments to put in the drop down.

**Comment by jeniferw** [comment]
import {
  MicrophoneIcon,
  CodeIcon,
  DownloadIcon,
  FireIcon,
  HeartIcon,
  LibraryIcon,
  MenuIcon,
  UserGroupIcon,
  XIcon,
} from '@heroicons/react/outline';




const datasets = [
  {
    name: 'Judges and Disclosures',
    description:
      'A rich structured database of judges, their backgrounds, and their financial entanglements.',
    href: '/projects/judge-db/',
    imgSrc: '/images/icons/judge-db.svg',
  },
  {
    name: 'Reporter Database',
    description:
      'The metadata and abbreviations for nearly every written reporter in American history. The heart of any citation parser.',
    href: '/projects/reporters-db/',
    imgSrc: '/images/icons/reporters-db.svg',
  },
  {
    name: 'Court Data',
    description: 'A collection of court metadata, standardized IDs, and parsers.',
    href: '/projects/courts-db/',
    imgSrc: '/images/icons/courts-db.svg',
  },
  {
    name: 'Oral Argument Recording Archive',
    description: 'The largest open collection of legal audio on the Internet..',
    href: '/projects/oral-arguments/',
    icon: MicrophoneIcon,
  },
  {
    name: 'Judge Portraits',
    description: 'Thousands of portraits of judges you can use in your projects.',
    href: '/projects/judge-pics/',
    icon: UserGroupIcon,
  },
  {
    name: 'Supreme Court Data',
    description: 'High quality data about Supreme Court opinions.',
    href: '/projects/supreme-court-data/',
    icon: LibraryIcon,
  },

];

**Comment by mlissner** [comment]
That looks pretty good. Can you go to the file where you want this change and use the pencil icon to change it? From there, Github will guide you through making a pull request, which is a fancy way of saying, "Here are some changes in my version of the code, can you please pull them into the regular version of the code?"

I'll review that PR, and then we'll be off to the races. I think my blog post about this from like a decade ago still holds up: 

https://michaeljaylissner.com/posts/2014/10/06/editing-on-github-a-non-technical-explainer/

**Comment by mlissner** [comment]
Oh hey, this is done.
