### ISSUE TITLE
update donate links on our websites

### ISSUE THREAD

**Issue by jeniferw** [freelawproject/free.law#146]
Update of all donate links to https://donate.free.law/forms/supportflp

**on free.law**
- in header
- in footer
- buttons on https://free.law/donate/other-ways/

**on CourtListener.com**
- in nav bar
- footer link
- footer button
- button on https://www.courtlistener.com/contribute/

**on Bots.law**
- in header
- button at bottom of homepage
- Donate Now link in footer

Any other places that we currently link to:
https://www.courtlistener.com/donate/
https://free.law/donate

**Comment by mlissner** [comment]
I think this is all set. @jeniferw, please reopen if you think we need more work on this. Thank you!
