### ISSUE TITLE
Add Suffolk talks to the blog

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#174]
Might as well! They were great. 

One is here: https://www.youtube.com/watch?v=EKf88kiE2jc

@jeniferw, do you think you could take a stab at this?

**Comment by jeniferw** [comment]
Absolutely!!

**Comment by jeniferw** [comment]
Draft of blog post: https://docs.google.com/document/d/1q7ufKBjG48Gk5pLN5UOVopR1nzTXKbTho4ajPJtmDxU/edit?usp=sharing

**Comment by mlissner** [comment]
You didn't want to include Colin's too?

**Comment by jeniferw** [comment]
I just found the video of his - so I need to revise.





Jenifer Whiston, Director of Philanthropy
***@***.***  | 970-331-6194
Book a meeting - https://calendly.com/flp-jenifer
Make a Donation <https://www.courtlistener.com/donate/> to support Free Law
Project
