### ISSUE TITLE
Fix 'jursidcition' typo in blog post

### ISSUE THREAD

**Issue by s-taube** [freelawproject/free.law#206]
In the [RECAP Archive Search blog](https://free.law/2024/01/18/new-recap-archive-search-is-live) post, `jursidcitionType` should be `jurisdictionType`. ("jursidcition" is a typo)

Make [edit here](https://github.com/freelawproject/free.law/blob/main/posts/2024/01/18/new-recap-archive-search-is-live.mdx).

**Comment by s-taube** [comment]
@mlissner can/should I create a PR for this? Any PR naming/description conventions I should stick to? Can discuss on a call if that's easier.

**Comment by mlissner** [comment]
Sure! Try editing in Github via the pencil icon. It'll make you make a branch or a fork, do that and just kind of click through until you have a PR. This is ten years old, but I think it mostly still holds up! (From back when I had time to blog!)

https://michaeljaylissner.com/posts/2014/10/06/editing-on-github-a-non-technical-explainer/

**Comment by mlissner** [comment]
Did I miss it? I don't think I saw where you changed this, Stephanie?
