### ISSUE TITLE
Add Rebecca and Michelle to free.law/team

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#218]
Rebecca Fordon's bio:

> Rebecca brings a unique perspective on legal technology and legal research, having transitioned into law librarianship after a successful career as a corporate bankruptcy attorney at an AmLaw 200 firm. A long-time volunteer with Free Law Project, her research interests have been greatly influenced by the organization’s mission, focusing currently on electronic court records, legal citators, and expanding open access to legal information. Rebecca frequently writes and speaks about legal technology and generative AI in the legal field and is a 2024 vLex Fastcase 50 honoree. She currently serves as a Law Librarian and Assistant Professor of Professional Practice at The Ohio State University’s Moritz College of Law, where she brings her expertise to both the classroom and the library. Rebecca holds degrees from Ohio Wesleyan University, Boston University School of Law, and UCLA and in her spare time loves crosswords, cooking, and cycling.

![Her photo](https://github.com/user-attachments/assets/bfa987bc-7531-492a-a6a0-ca1546108634)

And Michelle Ma's bio:

> Michelle Ma is an attorney and startup founder who is passionate about building legal technology for self-advocacy. She brings a decade of legal experience counseling technology companies on contracts, technology licensing, product and IP issues, and M&A. A former mechanical engineer, she worked as an executive and founder of several early stage startups before opening her own practice. 

![Her Photo](https://github.com/user-attachments/assets/ef3c029e-6e67-4eea-a420-88b2171731f2)

----

We'll need to convert and downsize the photos, etc, but should be straightforward. Please let me know what questions arise!

**Comment by elisa-a-v** [comment]
Only question is whether we're adding their roles? the rest of the team members have their role next to their names. Other than that, [it's ready](https://github.com/freelawproject/free.law/pull/220)

**Comment by mlissner** [comment]
Yes, they should be board members. Thank you!

**Comment by elisa-a-v** [comment]
Oh! I imagine ordering matters? in which position should each of them be listed?

**Comment by mlissner** [comment]
I think it doesn't matter too much, but me, Brian, Ansel, Rebecca, Michelle probably is best.
