### ISSUE TITLE
Do blog post about new opinions search

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#228]
In this blog post, we talked about the new recap search:

https://free.law/2024/01/18/new-recap-archive-search-is-live

Now we need to do one for opinions. It can probably copy the same style/format. Ideally, we'd get it done by Monday, so we can launch it at the same time it goes live.

**Comment by s-taube** [comment]
@mlissner [draft is here](https://docs.google.com/document/d/1cl1fJYuxn9H_JHVdA_0M3wF3JLhkJbKk3vSXKO4ZE2U/edit?tab=t.0)

**Comment by s-taube** [comment]
@mlissner Any clarity you can here add would be appreciated.

**Comment by s-taube** [comment]
Per mike on slack: "I think points 2, 3, 4, and 6 carry over, and you can add performance and scalability too. What's next is improved relevancy, additional search operators like /s, /p and /n, and other user experience enhancements."

**Comment by s-taube** [comment]
@mlissner is [this](https://docs.google.com/document/d/1cl1fJYuxn9H_JHVdA_0M3wF3JLhkJbKk3vSXKO4ZE2U/edit?tab=t.0) closer

**Comment by s-taube** [comment]
@mlissner I made updates based on your feedback. 

Questions -- 1) do you expect emoji searches to return results? I'm not having any luck. 2) you mentioned in your standup you will convert the post to a PR. Do you need anything else from me on this?
