### ISSUE TITLE
Add GivingTuesday banner on free.law

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#234]
Simple banner to run for one day at top of free.law:

**Today is GivingTuesday.** Your support of Free Law Project helps make the justice system more transparent and accessible to all. **[Donate Today!](https://donate.free.law/forms/givingtuesday)**

This should just run on Tuesday, December 3, 2024

**Comment by elisa-a-v** [comment]
Does this make sense or do we want something that pops out more? I'm not sure if we want the link to just be text; I feel like the button is more of a call to action than just underlining the text, but maybe we could use the button in mobile only and a link in bigger screens so we don't have two red buttons so close to each other.

![Image](https://github.com/user-attachments/assets/8b07677e-7d7a-43e3-946f-e89e75004536)
![Image](https://github.com/user-attachments/assets/26625891-9bf2-4435-8081-2e9a68e7da94)
![Image](https://github.com/user-attachments/assets/ef28ed97-8cd0-450b-9f54-7ef498beb381)

I thought maybe this could work too. it's more disruptive but it may be easier for people to notice..
![Image](https://github.com/user-attachments/assets/300d2c03-1ec8-4b60-80be-6604287a2591)
![Image](https://github.com/user-attachments/assets/5fb3ccce-f46e-4f95-95a2-e8503718a603)
