### ISSUE TITLE
Adding dedicated matching gift page to free.law

### ISSUE THREAD

**Issue by jeniferw** [freelawproject/free.law#241]

**Comment by jeniferw** [comment]
Adding a page to free.law about matching gifts - thinking free.law/donate/matching-gifts

[How to add the plugin to a dedicated matching gift page ](https://support.doublethedonation.com/portal/en/kb/articles/getting-started-understanding-plugin-settings)
[Example of a dedicated matching gift page.](https://www.catrescueclub.org/matching-gifts/)

Our settings - https://doublethedonation.com/members/#/setup/plugin-settings
I will need to add the person working on this to the users on our DTD account in order to see this.

Mock up of page (Still to come @jeniferw will do this)

Where to link page:
- should link in footer under SUPPORT FLP - put in list under Donations FAQ - link should be [Double Your Donation](https://free.law/donate/matching-gifts)
- [Donation FAQ](https://free.law/donate/help/) - 
Update: ![Image](https://github.com/user-attachments/assets/3785de8f-8986-4c8f-a407-c796c88ddb3b)
to read: 

> Do you accept matching donations from employers?
> 
> Yes! You can check if your employer has a giving program that we are already connected with [here](https://free.law/donate/matching-gifts). If your employer has a giving program, please use it so we can maximize your contribution. If your company is not found in the search, but you do have a matching gift program, please get in touch with our Director of Philanthropy, Jenifer Whiston, at jenifer@free.law and let us know if you or your company need any information from us to help set up the match.
>

**Comment by mlissner** [comment]
Making sure I understand this properly....the idea is:

1. Make a page at `/donate/matching-gifts/` that has the plugin on it. You're still working on some text for that page.

3. Add a link this new page to the footer. What should it say and where exactly should it go? 

3. Tweak the donation FAQ page to have the updated copy you provided above.

That right?

**Comment by jeniferw** [comment]
yes that sounds right.

link in footer should go under SUPPORT FLP - put in list under Donations FAQ - link should be [Double Your Donation](https://free.law/donate/matching-gifts)
![Image](https://github.com/user-attachments/assets/32f23b59-c1ce-4320-8cb4-7f39cd90ac4e)

**Comment by elisa-a-v** [comment]
@jeniferw since I'll be doing this one, could you add me to the DTD account please?

**Comment by jeniferw** [comment]
@elisa-a-v You should have received an email with a link to Double the Donation.
I will have the text for the body of the webpage to you by Monday.
Let me know if you need anything else.
Thank you!

**Comment by elisa-a-v** [comment]
@jeniferw I got the email and I could log into the dashboard, thank you!

only other thing I'd need besides the text for the body would be the title for the same page, which will appear as a header in the page, and as the tab title too, like "Help with Donations to Free Law Project" in the [Donations FAQ](https://free.law/donate/help)
![Image](https://github.com/user-attachments/assets/f4c20643-bd7f-4006-b662-6f75d6bf3b2e)

**Comment by elisa-a-v** [comment]
@jeniferw the new [Matching Gifts page](https://free.law/donate/matching-gifts/) is up! I updated the DTD settings with the URL too, let me know if I can help with anything else :)

**Comment by mlissner** [comment]
Looks great!
