### ISSUE TITLE
Re-do free.law G̶a̶t̶s̶b̶y̶ NextJS

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#44]
I've been investigating this for several months at this point and I think it's generally a good transition to make:

1. Pelican is not getting much usage any more and basic bugs are not getting fixed (for example, the cache feature is totally broken and nobody noticed except for me).
2. Gatsby has a ridiculously broad set of plugins that makes it really fast and powerful. Some of the starters are very good.
3. The new design in #39 needs a new home and I'm not at all interested in doing it in Pelican
4. Free.law is a useful playground to learn and experiment with new technologies. We're moving towards react a bit and considering using tailwindcss. Both are used in gatsby.
5. Nobody aside from me and poor, poor @flooie have successfully gotten pelican installed and working locally.

OTOH, I've been working on this here and there for several months, and I must confess that I've had a real difficult time getting traction on this, but I think with a good block of time I can make it happen. 

I'm going to use a [MoSCoW analysis](https://en.wikipedia.org/wiki/MoSCoW_method) to work on a partial feature list so we can decide when it's ready.

# MUST

 - [x] Have extremely good performance
 - [x] Have all the old blog posts
 - [x] Use old URLs or redirect them
 - [x] Have custom 404 page
 - [x] Support the new homepage in #39 
 - [x] Have a favicon
 - [x] ~Use Sitemap.xml files~ The linking is so good, I don't think it's needed.
 - [x] Support old links and downloads from Pelican format
 - [x] Do something with old Bootstrap HTML in markdown files
 - [x] Use the free.law domain
 - [x] Support HTTPS

# SHOULD

 - [ ] Be editable by somewhat lay people
 - [x] Send stats to Piwik
 - [x] #46

# COULD
 - [x] Support edits via some Netlify form or something
 - [x] #50
 - [x] Have a contact form
 - [x] Have a dark theme

# WON'T
 - [x] Use CSP headers

**Comment by litewarp** [comment]
Use NextJs instead of Gatsby. Less complicated, doesn't force you into GraphQL and with the SSR and SSG capabilities, there's no real advantage to gatsby anymore.

**Comment by mlissner** [comment]
> SSR

Selective serotonin reuptake?

**Comment by mlissner** [comment]
More todos:

 - [ ] Search for `btn` and similar bootstrap styles and re-do them
 - [ ] Search for captioned images and redo them
 - [ ] Find any remaining {filename} or other pelican syntax
 - [ ] Implement next-seo

**Comment by mlissner** [comment]
It's launched.

**Comment by mlissner** [comment]
Post launch:

 - [x] Check matomo
 - [ ] Sentry?
 - [x] Remove AWS CDN, Lambda, S3
