### ISSUE TITLE
Write a blog post about using DRF and HTMX

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/free.law#87]
We should write a blog post about the approach we took in using DRF and HTMX once the implementation on the webhooks is ready.

**Comment by mlissner** [comment]
Finally just did this by posting on reddit: https://www.reddit.com/r/django/comments/yee8l6/using_htmx_with_django_rest_framework/. No pressure, but feel free to join in if you have things to add or if I didn't get it right. Closing this for now though!
